### ISSUE TITLE
Allow access to endpoints which use kebab style

### ISSUE THREAD

**Issue by bilthon** [msdjl/pxapi#1]
Right now Paxful's API has some endpoints which are defined using hyphens, and because hyphens cannot be used as variable or function names in JS these endpoints cannot be accessed. 

Examples include:

offer/update-price
offer/turn-on
offer/turn-off

Solving this is not complicated and I'm willing to create a PR.

**Comment by msdjl** [comment]
You can access them using square brackets, like `px.offer['update-price']()`. It isn't looking cool but still lets you work with all the endpoints.

**Comment by msdjl** [comment]
Thanks for the PR. Published in 1.0.6.
